[colors]
transparent_background_colors = true

[cursor.style]
blinking = "Off"
shape = "Underline"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 0.95

[window.padding]
x = 5
y = 5
