#!/usr/bin/env bash

# global settings
yabai -m config mouse_follows_focus            off # on
yabai -m config focus_follows_mouse            off
yabai -m config window_placement               second_child
yabai -m config window_topmost                 off # on Make floating windows stay on top.
yabai -m config window_shadow                  off

yabai -m config window_opacity                 off #on
yabai -m config window_opacity_duration        0.0
yabai -m config active_window_opacity          1.0
yabai -m config normal_window_opacity          1.0 # 0.95

yabai -m config window_border                  on
yabai -m config window_border_width            5
yabai -m config active_window_border_color     0xff7ebad2
yabai -m config normal_window_border_color     0xff194052
yabai -m config insert_feedback_color          0xaad75f5f

yabai -m config split_ratio                    0.50
yabai -m config auto_balance                   off # on
yabai -m config mouse_modifier                 fn
yabai -m config mouse_action1                  move
yabai -m config mouse_action2                  resize
yabai -m config mouse_drop_action              stack

# space settings
yabai -m config layout                         bsp
yabai -m config external_bar                   off:25:0
yabai -m config bottom_padding                 15
yabai -m config left_padding                   15
yabai -m config right_padding                  15
yabai -m config top_padding                    15 # 0
yabai -m config window_gap                     10

# app rules
yabai -m rule --add app="^1Password 7$"        manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Alacritty"            border=off
# yabai -m rule --add app="Emacs"                manage=on
yabai -m rule --add app="Finder"               manage=off
yabai -m rule --add app="NordVPN"              manage=off

# window rules
yabai -m rule --add app=Slack                  space=5
yabai -m rule --add app=Spotify                space=6

# signals
yabai -m signal --add event=window_destroyed       action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
