#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus            off
yabai -m config focus_follows_mouse            off
yabai -m config window_origin_display          default
yabai -m config window_placement               second_child
# yabai -m config window_topmost                 off # on Make floating windows stay on top.
yabai -m config window_shadow                  off

yabai -m config window_opacity                 off
yabai -m config window_opacity_duration        0.0
yabai -m config active_window_opacity          1.0
yabai -m config normal_window_opacity          1.0 # 0.95

yabai -m config insert_feedback_color          0xaad75f5f

yabai -m config split_ratio                    0.50
yabai -m config auto_balance                   off # on
yabai -m config mouse_modifier                 fn
yabai -m config mouse_action1                  move
yabai -m config mouse_action2                  resize
yabai -m config mouse_drop_action              stack

# space settings
yabai -m config layout                         bsp
yabai -m config external_bar                   off:25:0
yabai -m config bottom_padding                 10
yabai -m config left_padding                   10
yabai -m config right_padding                  10
yabai -m config top_padding                    10 # 0
yabai -m config window_gap                     10

# app rules
yabai -m rule --add app="1Password"            manage=off
yabai -m rule --add app="^System Settings$"    manage=off
yabai -m rule --add app="Finder"               manage=off
yabai -m rule --add app="Focusrite Control 2"  manage=off

# window rules
yabai -m rule --add app=Dash                   space=3
yabai -m rule --add app=Slack                  space=5
yabai -m rule --add app=Obsidian               space=6
yabai -m rule --add app=Spotify                space=7

# signals
yabai -m signal --add event=window_destroyed       action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
