#!/bin/bash

# editor
alias e="subl"
alias emacs="emacs -nw"
alias vi="nvim"
alias vim="nvim"

# shell
alias ..="cd ../"
alias ...="cd ../../"
alias cp="cp -iv"
alias f="open -a Finder ./"
alias less="less -FSRXc"
alias ll="ls -lAh"
alias ls="ls -Gh"
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias path='echo -e ${PATH//:/\\n}'

# git
alias gb="git branch"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gg="git log --abbrev-commit --graph --pretty=format:'%Cred%h%Creset %C(bold blue)%an%Creset :%C(yellow)%d%Creset %s %Cgreen(%cr) %Creset'"
alias gs="git status"
alias gst="git status"

# ruby / rails
alias be="bundle exec"
alias berc="bundle exec rails c"
alias pr="pry-remote -w"

# kubernetes
alias kcp="kubectl cp"
alias kube="kubectl"
alias logs="kubectl logs"
alias secrets="kubectl get secrets"

# benchprep
alias berp="bundle exec primer restart"
# update for puma
alias restart="passenger-config restart-app"

alias api="cd ~/development/benchprep/benchprep-v2"
alias assets="cd ~/development/benchprep/benchprep-assets"
alias blueprint="cd ~/development/benchprep/benchprep-course-publisher"
alias boost="cd ~/development/benchprep/benchprep-instructor-dashboard"
alias development="cd ~/development"benchprep/
alias infrastructure="cd ~/development/benchprep/infrastructure"
alias marketing="cd ~/development/benchprep/benchprep-marketing"
alias reporting="cd ~/development/benchprep/benchprep_reporting_api"
alias sso="cd ~/development/benchprep/benchprep-sso"
alias support="cd ~/development/benchprep/benchprep-support"
alias teachers="cd ~/development/benchprep/benchprep-teachers"
alias v2="cd ~/development/benchprep/benchprep-v2"
alias webapp="cd ~/development/benchprep/benchprep-webapp"
