#!/bin/bash

# editor
alias e="subl"
alias emacs="emacs -nw"
alias vi="nvim"
alias vim="nvim"

# shell
alias cp="cp -iv"
alias f="open -a Finder ./"
alias ll="ls -lah"
alias ls="ls -Gh"
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias path='echo -e ${PATH//:/\\n}'

# git
alias gst="git status"

alias gs="git status"
alias ga="git add -A ."
alias gc="git commit"
alias gb="git branch"
alias gd="git diff"
alias gco="git checkout"
alias gp="git push"
alias gl="git pull"
alias gm="git merge"
alias gg="git log --graph --pretty=format:'%C(bold red)%h%Creset -%C(bold yellow)%d%Creset %s %C(bold green)(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
# git log --all --graph --pretty=format:"%Cred%h%Creset %C(bold blue)%an%Creset :%C(yellow)%d%Creset %s %Cgreen(%cr) %Creset" --abbrev-commit

# ruby / rails
alias be="bundle exec"
alias berc="bundle exec rails c"
alias pr="pry-remote -w"

# kubernetes
alias kcp="kubectl cp"
alias kube="kubectl"
alias logs="kubectl logs"
alias secrets="kubectl get secrets"

# benchprep
alias berp="bundle exec primer restart"
alias restart="passenger-config restart-app"

alias api="cd ~/development/benchprep-v2"
alias assets="cd ~/development/benchprep-assets"
alias blueprint="cd ~/development/benchprep-course-publisher"
alias boost="cd ~/development/benchprep-instructor-dashboard"
alias development="cd ~/development"
alias infrastructure="cd ~/development/infrastructure"
alias marketing="cd ~/development/benchprep-marketing"
alias reporting="cd ~/development/benchprep_reporting_api"
alias sso="cd ~/development/benchprep-sso"
alias support="cd ~/development/benchprep-support"
alias teachers="cd ~/development/benchprep-teachers"
alias v2="cd ~/development/benchprep-v2"
alias webapp="cd ~/development/benchprep-webapp"
