#!/bin/bash

DOTFILES_PATH=~/development/dotfiles
BASH_SRC_PATH=$DOTFILES_PATH/bash

. "$BASH_SRC_PATH"/aliases
. "$BASH_SRC_PATH"/functions
. "$BASH_SRC_PATH"/prompt

export EDITOR="subl"
export HISTCONTROL=ignoreboth:erasedups

# append history file
shopt -s histappend

# edit this folder
alias dot="cd $DOTFILES_PATH"
# reload
alias rl="source ~/.profile; echo '~/.profile reloaded.'"

# osx
export CLICOLOR=1
export LSCOLORS=ExGxdxDxCxegedhbadaced

# recursively delete .DS_Store
alias dsstore="find . -name '*.DS_Store' -type f -ls -delete"
