#!/bin/bash

YELLOW=$(tput setaf 3)
LIGHTRED=$(tput setaf 9)
ORANGE=$(tput setaf 172)
PURPLE=$(tput setaf 141)
WHITE=$(tput setaf 256)
BOLD=$(tput bold)
RESET=$(tput sgr0)

PROMPT_SYMBOL="❯"
GIT_DIRTY_SYMBOL="✗"

function git_info() {
  # check if we're in a git repo
  git rev-parse --is-inside-work-tree &>/dev/null || return
  # quickest check for what branch we're on
  branch=$(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||')
  # check if it's dirty (via github.com/sindresorhus/pure)
  dirty=$(git diff --quiet --ignore-submodules HEAD &>/dev/null; [ $? -eq 1 ] && echo -e $GIT_DIRTY_SYMBOL)

  echo $RESET $LIGHTRED$branch$RESET$YELLOW $dirty
}

function usernamehost() {
  if [ "$SSH_TTY" ]; then
    echo "${PURPLE}$USER@$HOSTNAME${RESET}:";
  fi
}

PS1="\$(usernamehost)\[$ORANGE\]\w\$(git_info)\[$RESET\] $PROMPT_SYMBOL "
